import Head from 'next/head'
import { MainView } from '@/components/MainView'
import { useStageSize } from '@/components/MainView/stageSize'

export default function Home() {
  const [_, setStagetSize] = useStageSize()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <MainView width={450} height={800} />
      </main>
    </>
  )
}
